### ISSUE TITLE
How do I scroll through palletes?

### ISSUE THREAD

**Issue by idr1ss** [TodePond/CellPond#302] opened 2023-06-25 00:57 UTC
Currently theres a limit to how many palletes i can create and i don't know how to fix this. Please help me!

**Comment by VINDI777** [comment] 2023-07-02 20:05
what is a "palette"?

**Comment by TeraByte-Official** [comment] 2023-07-07 01:06
I think you mean paddles?
That's simple: just ctrl+scroll to zoom, and alt+scroll to scroll.

**Comment by TodePond** [comment] 2023-10-17 17:58
Currently you can hold 'alt' or 'option' and scroll the mouse wheel. I think that's it
We should make it scrollable in the normal way though 
Duplicate of #53

**Closed by TodePond** 2023-10-17 17:58 UTC
